
// RLE
.label rreadV = reserve()
.label rrunByte = reserve(1)
.label rrunCount = reserve(1)
.label breadV = reserve()
.label brunByte = reserve(1)
.label brunCount = reserve(1)
.label mreadV = reserve()
.label mrunByte = reserve(1)
.label mrunCount = reserve(1)
.label column = reserve(1)
.label colbyte = reserve(1)
.label row = reserve(1)
.label wrV = reserve()
.label wrV2 = reserve()
// DblBuf
.label vicBank = reserve(1)
// Frame
.label frdiv = reserve(1)
.label frspd = reserve(1)
.label aniptr = reserve()
.label cfreq = reserve()
.label phase = reserve(1)
.label phcount = reserve(1)
.label jumping = reserve(1)
.label keyheld = reserve(1)
.label seconds = reserve(1)  
.label secondsc = reserve(1)  
.label level = reserve(1)
.label xscroll = reserve(1)
.label scrolling = reserve()
.label nextFrameISR = reserve()
.label ftmp = reserve(1)
// Game
.label powerLevel = reserve(1)
.label lilypos = reserve(1)
// SID
.label SIDctrl = reserve(3)
// SprLib
.label lsarg = reserve(2)
// Unroll (temp)
.label unrAddr = reserve()
.label unwAddr = reserve()
.label uncAddr = reserve()
.label unSize = reserve()
